### ISSUE TITLE
0.2.0 and 0.3.0 of amqp has been released.

### ISSUE THREAD

**Issue by SkipMike** [CJPoll/subscribex#11]
The latest stable release depends on version 0.1.5 of amqp. In the meantime, 0.2.0 and 0.3.0 have been released. 

Does that mean that you can release 0.8.0, which has support for erlang 19?

**Comment by podium-mu** [comment]
Indeed! I've had an RC up for 0.8.0 which depends on `0.2.0`. Check it out and let me know how it works: https://hex.pm/packages/subscribex/0.8.0-rc.0

**Comment by CJPoll** [comment]
Indeed! I've had an RC up for 0.8.0 which depends on 0.2.0. Check it out and let me know how it works: https://hex.pm/packages/subscribex/0.8.0-rc.0

**Comment by CJPoll** [comment]
I wasn't aware 0.3.0 had been released. I'll look at that this weekend and see if I can get an rc-1 up this weekend using 0.3.0.

**Comment by SkipMike** [comment]
Sweet, thanks.

**Comment by SkipMike** [comment]
It looks like the release candidate doesn't support erlang 20, probably because ampq 0.2.0 doesn't. However, it looks like amqp 0.3.0 does support erlang 20, so hopefully it all comes together when you give it a try.

**Comment by CJPoll** [comment]
New Release Candidate Cut: https://hex.pm/packages/subscribex/0.8.0-rc.1

**Comment by CJPoll** [comment]
I did some testing, and it doesn't look like the AMQP API changed (at least not any functions this lib uses), but please let me know if something goes wrong with it.

There are breaking changes from `0.8.0-rc.0`. They can be found in the release description: https://github.com/CJPoll/subscribex/releases

**Comment by CJPoll** [comment]
0.8.0 was released some time ago. Closing the issue.
